### ISSUE TITLE
statement of need for documentation

### ISSUE THREAD

**Issue by jacobmerson** [gianthk/ciclope#15]
As per JOSS requirements, please add the statement of need to your documentation webpage.

**Comment by gianthk** [comment]
Actually, I was sure that the statement of need was part of the paper checklist, not doc checklist. I can add a similar statement to the readthedocs page if you recommend, although I don't think it is common (I don't see it often on doc pages).
can you please point to the exact JOSS requirement?

**Comment by jacobmerson** [comment]
Please review the checklist here: https://joss.readthedocs.io/en/latest/review_checklist.html
Or, here is the "interactive" one on the github issue: https://github.com/openjournals/joss-reviews/issues/4952#issuecomment-1322355737

**Comment by gianthk** [comment]
OK clear.

**Comment by gianthk** [comment]
@jacobmerson I just pushed updated readthedocs pages with a statement of need. I added a shorter version also to the github readme file.
