### ISSUE TITLE
Error in function mesh2tetrafe when running example ciclope_ex02_tetrauFE_CalculiX 

### ISSUE THREAD

**Issue by bennyschnabel** [gianthk/ciclope#18]
When running the ciclope_ex02_tetrauFE_CalculiX example, the error message "TypeError: 'CellBlock' object is not subscriptable" appears. The error message occurs when trying to create the CalculiX FE input file.

![Screenshot from 2023-03-28 18-40-23](https://user-images.githubusercontent.com/348447/228309510-50cfef29-f873-4434-841e-def0a96aae40.png)

**Comment by gianthk** [comment]
@bennyschnabel I will close this one since it is a known issue with `meshio>5.0.0`. See my reply above.
