### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jacobmerson** [gianthk/ciclope#8]
I'm working on the joss review and I'm having some installation difficulties with pip and "optional" dependencies.

1. using `pip install ciclope[all]` gives me the error `no matches found: ciclope[all]`. I haven't used options on a `pip install` before, so I'm not sure what this should look like.
2. There are a bunch of dependencies that are needed beyond what's installed by default. However, `ciclope -h` can't run without them, so I presume they are not optional. They are `dxchange`, `scipy`, `scikit-image`, `pypng`
3. `pycgal` required lots of manual intervention to get things linking and building. Nothing you can do about this, but it certainly makes the installation harder.

**Comment by jacobmerson** [comment]
Leaving this here so it links to the joss review: https://github.com/openjournals/joss-reviews/issues/4952

**Comment by gianthk** [comment]
I have removed the dependency to dxchange since it was irrelevant

**Comment by gianthk** [comment]
waiting @jacobmerson to close this issue if installation procedures is OK
#openjournals/joss-reviews#4952

**Comment by jacobmerson** [comment]
`matplotlib` is listed as an optional dependency, but `ciclope -h` fails if it is not installed.

**Comment by gianthk** [comment]
> `matplotlib` is listed as an optional dependency, but `ciclope -h` fails if it is not installed.
@jacobmerson thanks: it was corrected in v1.3.2. should be OK now

**Comment by jacobmerson** [comment]
@gianthk is version 0.10.6 of pygalmesh strictly required? I'm having all sorts of installation issues with that version. I tried running ciclope with 0.10.7 and didn't see any obvious issues crop up.

**Comment by gianthk** [comment]
@jacobmerson did all unittest pass with pygalmesh==0.10.7?
I am trying to test it in a parallel env. will let you know

**Comment by jacobmerson** [comment]
@gianthk they did pass. I might suggest setting `pygalmesh>=0.10.7`

**Comment by gianthk** [comment]
testing this to be 100% sure before updating the requirement

**Comment by gianthk** [comment]
done. dep updated to `pygalmesh>=0.10.6`
